apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: banco-digital
  labels:
    app: prometheus
    component: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ["localhost:9090"]

      - job_name: banco-digital-gateway
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ["gateway:80"]
            labels:
              service: gateway

      - job_name: banco-digital-identity
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ["identity:8081"]
            labels:
              service: identity

      - job_name: banco-digital-core
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ["core:8080"]
            labels:
              service: core-banking

      - job_name: banco-digital-audit
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ["audit:8082"]
            labels:
              service: audit

      - job_name: banco-digital-reporting
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ["reporting:8083"]
            labels:
              service: reporting
