apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: banco-digital
  labels:
    component: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      external_labels:
        cluster: 'banco-digital'

    scrape_configs:
      - job_name: 'banco-digital-gateway'
        static_configs:
          - targets: ['gateway:80']
        metrics_path: '/actuator/prometheus'

      - job_name: 'banco-digital-identity'
        static_configs:
          - targets: ['identity:8081']
        metrics_path: '/actuator/prometheus'

      - job_name: 'banco-digital-core'
        static_configs:
          - targets: ['core:8080']
        metrics_path: '/actuator/prometheus'

      - job_name: 'banco-digital-audit'
        static_configs:
          - targets: ['audit:8082']
        metrics_path: '/actuator/prometheus'

      - job_name: 'banco-digital-reporting'
        static_configs:
          - targets: ['reporting:8083']
        metrics_path: '/actuator/prometheus'
