apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-banking-service
  labels:
    app: core-banking
spec:
  replicas: 3
  selector:
    matchLabels:
      app: core-banking
  template:
    metadata:
      labels:
        app: core-banking
    spec:
      containers:
        - name: core-banking
          image: gcr.io/banco-digital/core-banking:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://core-db-service:5432/banco_digital_core"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
            - name: IDENTITY_SERVICE_URL
              value: "http://identity-service:8080"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"