apiVersion: v1
kind: ConfigMap
metadata:
  name: audit-config
  namespace: banco-digital
data:
  APP_PROFILE: "docker"
  APP_PORT: "8082"
  DB_NAME: "banco_digital_audit"
  EVENTS_TOPIC: "banco-digital-events"
  AUDIT_DLQ_TOPIC: "audit-events-dlq"
  AUDIT_PENDING_TOPIC: "audit-events-pending"
