apiVersion: v1
kind: ConfigMap
metadata:
  name: reporting-config
  namespace: banco-digital
data:
  APP_PROFILE: "docker"
  APP_PORT: "8083"
  DB_NAME: "banco_digital_reporting"
  EVENTS_TOPIC: "banco-digital-events"
  REPORTING_PENDING_TOPIC: "reporting-events-pending"
  REPORTING_DLQ_TOPIC: "reporting-events-dlq"
