apiVersion: v1
kind: Service
metadata:
  name: identity
  namespace: banco-digital
  labels:
    app: identity
spec:
  type: ClusterIP
  selector:
    app: identity
  ports:
    - port: 8081
      targetPort: 8081
      name: http
